import streamlit as st
import requests
import json
import fitz
from fpdf import FPDF
import base64
from PIL import Image
import io
import time

# --- 1. إعدادات PDF الاحترافية ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.set_text_color(0, 210, 255)
        self.cell(0, 10, 'MODINEMATH AI - GLOBAL ACADEMIC PROOF', 0, 1, 'C')
        self.set_draw_color(146, 254, 157)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by MODINEMATH V9.0 | Youness Modine - Page {self.page_no()}', 0, 0, 'C')

# --- 2. التصميم النهائي "الضوء الساحر" (Custom CSS) ---
st.set_page_config(page_title="MODINEMATH AI", page_icon="🛡️", layout="wide")

st.markdown("""
    <style>
    /* الخلفية والتنسيق العام */
    .stApp {
        background: radial-gradient(circle at 20% 20%, #1a1c2c, #050505);
        color: #e0e0e0;
    }
    
    /* العنوان الرئيسي المتوهج */
    .main-title {
        font-size: 65px;
        font-weight: 900;
        background: linear-gradient(90deg, #00d2ff, #92fe9d, #00d2ff);
        background-size: 200% auto;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        animation: shine 3s linear infinite;
        text-align: center;
        margin-bottom: 5px;
    }
    
    @keyframes shine {
        to { background-position: 200% center; }
    }

    .university-tag {
        text-align: center;
        color: #8892b0;
        font-size: 1.1rem;
        letter-spacing: 2px;
        margin-bottom: 40px;
        text-transform: uppercase;
    }

    /* صناديق المعلومات */
    .info-card {
        background: rgba(255, 255, 255, 0.05);
        border-radius: 15px;
        padding: 20px;
        border: 1px solid rgba(0, 210, 255, 0.2);
        margin-bottom: 20px;
    }

    /* الأزرار السيبرانية */
    div.stButton > button {
        background: linear-gradient(45deg, #00d2ff, #3a7bd5);
        color: white;
        border: none;
        border-radius: 10px;
        padding: 15px 30px;
        font-weight: bold;
        font-size: 18px;
        width: 100%;
        transition: 0.4s;
        box-shadow: 0 4px 15px rgba(0, 210, 255, 0.3);
    }
    
    div.stButton > button:hover {
        transform: translateY(-3px);
        box-shadow: 0 8px 25px rgba(0, 210, 255, 0.6);
        background: linear-gradient(45deg, #92fe9d, #00d2ff);
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. المنطق البرمجي (The Engine) ---

GROQ_API_KEY = st.secrets["GROQ_API_KEY"]

def query_groq(payload):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"}
    response = requests.post(url, headers=headers, json=payload, stream=True)
    for line in response.iter_lines():
        if line:
            decoded = line.decode('utf-8').replace('data: ', '')
            if decoded == '[DONE]': break
            try:
                chunk = json.loads(decoded)
                yield chunk['choices'][0]['delta'].get('content', '')
            except: continue

# --- 4. واجهة المستخدم النهائية ---
st.markdown('<h1 class="main-title">MODINEMATH AI</h1>', unsafe_allow_html=True)
st.markdown('<p class="university-tag">University Ibn Tofail | Faculty of Sciences</p>', unsafe_allow_html=True)

with st.sidebar:
    st.markdown("### ⚙️ Engine Settings")
    lang = st.selectbox("🌐 Solution Language", ["Arabic", "French", "English", "Russian", "Chinese", "Japanese", "Korean", "Hindi"])
    level = st.select_slider("Academic Rigor", options=["Primary", "Lycée", "Licence", "Master (MMP)"])
    st.markdown("---")
    st.info("Status: Online (Groq Cloud)")
    st.image("https://img.icons8.com/fluency/96/artificial-intelligence.png", width=60)

# تقسيم الشاشة لجمالية أكبر
col1, col2 = st.columns([1, 1.5])

with col1:
    st.markdown('<div class="info-card">', unsafe_allow_html=True)
    st.subheader("📥 Input Source")
    uploaded_file = st.file_uploader("Drop PDF or Image", type=["pdf", "png", "jpg", "jpeg"])
    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    if uploaded_file:
        file_type = uploaded_file.name.split('.')[-1].lower()
        if st.button("🚀 EXECUTE GLOBAL SOLVER"):
            full_solution = ""
            solution_area = st.empty()
            
            with st.spinner("AI is thinking..."):
                if file_type in ["png", "jpg", "jpeg"]:
                    st.toast("Vision Mode Activated", icon="👁️")
                    img_b64 = base64.b64encode(uploaded_file.read()).decode('utf-8')
                    payload = {
                        "model": "llama-3.2-11b-vision-preview",
                        "messages": [{"role": "user", "content": [{"type": "text", "text": f"Solve this math in {lang} at {level} level. Use LaTeX."}, {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}}]}],
                        "stream": True
                    }
                else:
                    st.toast("PDF Text Mode Activated", icon="📄")
                    doc = fitz.open(stream=uploaded_file.read(), filetype="pdf")
                    context = "\n".join([page.get_text() for page in doc])
                    payload = {
                        "model": "llama3-70b-8192",
                        "messages": [{"role": "system", "content": f"Master Mathematician. Solve in {lang} ({level}). Use LaTeX."}, {"role": "user", "content": context}],
                        "stream": True
                    }

                st.markdown("### 🎓 Academic Output")
                for chunk in query_groq(payload):
                    full_solution += chunk
                    solution_area.markdown(full_solution + "▌")
                solution_area.markdown(full_solution)

                # --- زر تحميل PDF الاحترافي ---
                pdf = PDF()
                pdf.add_page()
                pdf.set_font("Arial", size=12)
                pdf.multi_cell(0, 10, full_solution.encode('latin-1', 'replace').decode('latin-1'))
                pdf_bytes = pdf.output(dest='S').encode('latin-1')
                st.download_button("📥 Download Official Proof (PDF)", data=pdf_bytes, file_name=f"MODINEMATH_{lang}.pdf")

st.markdown("---")

st.caption("© 2026 MODINEMATH AI - The Future of Mathematical Intelligence.")
